places=['New Zealand','Australia','Japan','Ireland','Columbia']
print(places)
print(sorted(places))
print(places)
print(sorted(places,reverse=True))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)
print(f"There are {len(places)} places where I definetly want to visit once in my Life")
